Everest backup recommendation removed, PHP error fixed, typography options added etc.
- Removed: Everest backup plugin recommendation.
- Removed: Options, `Enable Cursive Site Title`, `Enable Cursive Post Meta`, and `Enable Lazy Loading`.
- Removed: jQuery plugin, Lazysize.
- Fixed: Issue with customizer options, `Display Featured Image`.
- Fixed: PHP error - `PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function get_day_link(), 1 passed in /wp-content/themes/cream-magazine/third-party/breadcrumbs.php on line 802 and exactly 3 expected.`
- Fixed:  Missing `=` after an instance of `value` attribute in an `input` tag in `value"' . get_search_query() . '"`.
- Fixed: JS issue of preloader.
- Fixed: Minor CSS issues.
- Updated: YouTube icon in social links of header and social widget.
- Updated: WPCS maintained.
- Updated: Post comments meta linked to comment section of the post.
- Added: Typography options for body, headings, site title, and author meta.